### ISSUE TITLE
Incorporate homerun ROH calling

### ISSUE THREAD

**Issue by hardingnj** [cggh/scikit-allel#111]
I have some ROH calling code in hardingnj/phasing. 

Might be useful to pull this into scikit allel?

The way I would plan to do this is to add a new function to .stats then additionally write a script that is able to run this on VCF or genotype text files.

I'd plan to make the function simply return a simple 2D array of start/stops, but perhaps could be a simple class with some methods to calc FROH (> x kb) s and count of ROHs (> x kb).

**Comment by hardingnj** [comment]
So, this is proving a bit trickier than anticipated. The HMM is slow ~5 minutes per sample on a 41Mb chromosome. This is mainly because we use a multinomial HMM with each base being an observation. 

I'm thinking to incorporate into scikit it should be a) faster and b) extensible to species with larger genomes. Currently, I don't think it's practical to run on humans for example. Here we would create a 300m array (chr1) and would take a significant period. It may be worth approximating by regions, but would require a rethink on how inaccessible regions are handled.

Also, I guess this ties into the use of `is_accessible`, which becomes more difficult with larger datasets. 

Another possibility is to break into chunks and deal with any extra processing time.

**Comment by alimanfoo** [comment]
Done in #127.
