### ISSUE TITLE
Issue with selecting from variants

### ISSUE THREAD

**Issue by ellenelle** [cggh/scikit-allel#169]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-103-ec648c42af76> in <module>()
----> 1 variants_snps = variants.compress(snp_selection)

~/miniconda3/envs/pyenv1/lib/python3.5/site-packages/allel/chunked/core.py in compress(self, condition, axis, out, blen, storage, create, **kwargs)
    953                  **kwargs):
    954         out = compress_table(condition, self, axis=axis, out=out, blen=blen, storage=storage,
--> 955                              create=create, **kwargs)
    956         return type(self)(out)
    957 

~/miniconda3/envs/pyenv1/lib/python3.5/site-packages/allel/chunked/core.py in compress_table(condition, tbl, axis, out, blen, storage, create, **kwargs)
    349                                                expectedlen=nnz, **kwargs)
    350             else:
--> 351                 out.append(res)
    352     return out
    353 

~/miniconda3/envs/pyenv1/lib/python3.5/site-packages/allel/chunked/storage_zarr.py in append(self, data)
     98         names, columns = _util.check_table_like(data, names=self.names)
     99         for n, c in zip(names, columns):
--> 100             self.grp[n].append(c)
    101 
    102 

~/miniconda3/envs/pyenv1/lib/python3.5/site-packages/zarr/core.py in append(self, data, axis)
    997 
    998         """
--> 999         return self._write_op(self._append_nosync, data, axis=axis)
   1000 
   1001     def _append_nosync(self, data, axis=0):

~/miniconda3/envs/pyenv1/lib/python3.5/site-packages/zarr/core.py in _write_op(self, f, *args, **kwargs)
    884             err_read_only()
    885 
--> 886         return self._synchronized_op(f, *args, **kwargs)
    887 
    888     def resize(self, *args):

~/miniconda3/envs/pyenv1/lib/python3.5/site-packages/zarr/core.py in _synchronized_op(self, f, *args, **kwargs)
    868         if self._synchronizer is None:
    869             self._refresh_metadata_nosync()
--> 870             return f(*args, **kwargs)
    871 
    872         else:

~/miniconda3/envs/pyenv1/lib/python3.5/site-packages/zarr/core.py in _append_nosync(self, data, axis)
   1031             for i in range(len(self._shape))
   1032         )
-> 1033         self[append_selection] = data
   1034 
   1035         return new_shape

~/miniconda3/envs/pyenv1/lib/python3.5/site-packages/zarr/core.py in __setitem__(self, item, value)
    617                 # put data
    618                 self._chunk_setitem(cidx, chunk_selection,
--> 619                                     value[value_selection])
    620 
    621     def _chunk_getitem(self, cidx, item, dest):

~/miniconda3/envs/pyenv1/lib/python3.5/site-packages/zarr/core.py in _chunk_setitem(self, cidx, item, value)
    691         # synchronization
    692         if self._synchronizer is None:
--> 693             self._chunk_setitem_nosync(cidx, item, value)
    694         else:
    695             # synchronize on the chunk

~/miniconda3/envs/pyenv1/lib/python3.5/site-packages/zarr/core.py in _chunk_setitem_nosync(self, cidx, item, value)
    754 
    755                 # decode chunk
--> 756                 chunk = self._decode_chunk(cdata)
    757                 if not chunk.flags.writeable:
    758                     chunk = chunk.copy(order='K')

~/miniconda3/envs/pyenv1/lib/python3.5/site-packages/zarr/core.py in _decode_chunk(self, cdata)
    787             chunk = chunk.view(self._dtype)
    788         else:
--> 789             chunk = np.frombuffer(chunk, self._dtype)
    790 
    791         # reshape

ValueError: cannot create an OBJECT array from memory buffer

**Comment by alimanfoo** [comment]
Believe this should be resolved upstream in zarr, closing as not sure how to reproduce.
