### ISSUE TITLE
allel.write_vcf() function

### ISSUE THREAD

**Issue by kennethriva** [cggh/scikit-allel#196]
Is there a way to write a VCF file after a query selection?.

**Comment by alimanfoo** [comment]
Hi @kennethriva, this is partially implemented, the function allele.write_vcf() can write out variants but doesn't currently support sample data (i.e., genotype calls). Docs here: http://scikit-allel.readthedocs.io/en/latest/io.html#allel.write_vcf

Contributions adding full support for writing VCF including sample data would be welcome.

**Comment by kennethriva** [comment]
Thanks!
What do you mean by "writting out variants"  but not samples?. I mean, in which way writting variants actually work. I am having troubles trying to understand the docs, if you could give me an example would be useful.

Once again thanks a lot.

**Comment by alimanfoo** [comment]
Apologies for non-existent documentation. The write_vcf() function can write out data to the fixed fields (CHROM, POS, ID, etc.) and the INFO field, but does not support writing any sample columns (i.e., calldata).

Here is a rough example:

```
In [1]: import allel

In [2]: import numpy as np

In [3]: callset = dict()

In [4]: callset['variants/CHROM'] = np.array(['2R', '2R', '2L', '3R', 'X'])

In [5]: callset['variants/POS'] = np.array([12, 45, 267, 142, 2345])

In [6]: callset['variants/REF'] = np.array(['A', 'C', 'T', 'G', 'A'])

In [7]: callset['variants/ALT'] = np.array([['T', ''], ['A', 'CTA'], ['G', ''], ['C', 'T'], ['G', '']])

In [8]: callset['variants/FILTER_PASS'] = np.array([True, False, True, True, False])

In [9]: callset['variants/DP'] = np.array([23, 34, 45, 56, 67])

In [10]: allel.write_vcf(path='example.vcf', callset=callset)

In [11]: !cat example.vcf
##fileformat=VCFv4.1
##fileDate=20180703
##source=scikit-allel-1.1.10
##INFO=<ID=DP,Number=1,Type=Integer,Description="">
##FILTER=<ID=PASS,Description="">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
2R	12	.	A	T,	.	PASS	DP=23
2R	45	.	C	A,CTA	.	PASS	DP=34
2L	267	.	T	G,	.	PASS	DP=45
3R	142	.	G	C,T	.	PASS	DP=56
X	2345	.	A	G,	.	PASS	DP=67
```
