### ISSUE TITLE
allel.stats.ld.rogers_huff_r doesn't respect fill keyword

### ISSUE THREAD

**Issue by hardingnj** [cggh/scikit-allel#197]
I might be misunderstanding the fill keyword, but would expect cell `[0]` of `ld` in this case to be `7.3` not `np.nan`

```python
import allel
import numpy as np
d = np.zeros((20, 5))
d[:, 1] = 1
d[1] = -1
ld = allel.stats.ld.rogers_huff_r(d[:], fill=7.3)
ld
```

```python
q = d.astype("i1")
allel.stats.ld.gn_pairwise_corrcoef_int8(q[:], fill=7.3)
```
Happy to dig into this if this is unexpected behaviour.

**Comment by hardingnj** [comment]
Version `1.1.10` btw

**Comment by alimanfoo** [comment]
Relevant code starts here: https://github.com/cggh/scikit-allel/blob/master/allel/opt/stats.pyx#L53

This function computes the correlation for a pair of variants. IIRC, the fill value is used in the case where the variance within either variant in a pair is zero, i.e., the variant has the same genotype for all individuals. At least that's what's supposed to happen. Maybe there is some other numerical condition that can result in a nan even if variance is non-zero for both variants. I adapted that code from somewhere, can't remember where now, should have left a reference.

**Comment by alimanfoo** [comment]
In other words, this could do with another pair of eyes on it if you have time.

**Comment by alimanfoo** [comment]
Ah, thanks. So maybe this can be fixed by adding a check for ``n == 0``? E.g.:

```
    if n == 0 or v0 == 0 or v1 == 0:
        r = fill
```

Please do fix, and if you could add a unit test too that would be awesome.

**Comment by alimanfoo** [comment]
FWIW I decided it would just be simpler to remove the `fill` argument and always using `NaN`. Have also added some tests and the check suggested above.
