### ISSUE TITLE
ImportError: No module named 'allel' 

### ISSUE THREAD

**Issue by meddly** [cggh/scikit-allel#203]
>>> import allel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'allel'

**Comment by alimanfoo** [comment]
Hi there, this error means that scikit-allel is not installed in the Python interpreter that you've run. Could you say how you installed scikit-allel, and how you launched the Python interpreter to get this error?

**Comment by alimanfoo** [comment]
Can I ask, is this the first time you have installed Anaconda? Have you
managed to install and import any other packages? Did you create and
activate a conda environment before you installed scikit-allel? Did you
also activate the same conda environment before launching the Python
interpreter?

A common mistake is to install a package (e.g., scikit-allel) into a
different conda environment from the one you then use to launch the
interpreter. What can also happen (e.g., on Linux) is that you install a
package with conda but then launch the system Python interpreter (which is
completely separate from Anaconda).

I'd suggest reading my tutorial here, particularly from the section on
"creating an environment":
http://alimanfoo.github.io/2017/05/18/installing-python.html

Hth.


-- 
If I do not respond to an email within a few days, please feel free to
resend your email and/or contact me by other means.

Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health
Big Data Institute
Li Ka Shing Centre for Health Information and Discovery
Old Road Campus
Headington
Oxford
OX3 7LF
United Kingdom
Phone: +44 (0)1865 743596 or +44 (0)7866 541624
Email: alimanfoo@googlemail.com
Web: http://a <http://purl.org/net/aliman>limanfoo.github.io/
Twitter: @alimanfoo <https://twitter.com/alimanfoo>

**Comment by meddly** [comment]
Thank you so much. I re-installed the scikit-allel after verifying the activation of the environment. Now it works.

**Comment by alimanfoo** [comment]
Great!

**Comment by youlongjizi** [comment]
The software semms to exists secret BUG here, I can't solve it before having tried it many times.

**Comment by hardingnj** [comment]
> Hi there, this error means that scikit-allel is not installed in the Python interpreter that you've run. Could you say how you installed scikit-allel, and how you launched the Python interpreter to get this error?

**Comment by youlongjizi** [comment]
> > Hi there, this error means that scikit-allel is not installed in the Python interpreter that you've run. Could you say how you installed scikit-allel, and how you launched the Python interpreter to get this error?

Thanks for your reply! Having confirmed all software installed correctly, I sovle it after using relative path for output file. But, I am still confused for the error when using absolute path.
