### ISSUE TITLE
`alllel.vcf_to_zarr()` could preserve descriptions of fields from VCF header

### ISSUE THREAD

**Issue by hardingnj** [cggh/scikit-allel#265]
Unsure of where annotations could go, but currently they are lost when we convert `vcf` to `zarr`. This might cause downstream users issues with data provenance etc.

**Comment by alimanfoo** [comment]
IIRC the field descriptions do get copied across and become attributes on the arrays. E.g., [here](https://github.com/cggh/scikit-allel/blob/master/allel/io/vcf_read.py#L831) and [here](https://github.com/cggh/scikit-allel/blob/master/allel/io/vcf_read.py#L487). Is that what you were thinking?

**Comment by hardingnj** [comment]
Yes! That's great thanks, I didn't know about `calldata[chrom]["variants/HRun"].attrs["Description"]`
