### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by travc** [cggh/scikit-allel#273]
Really not very important, but...
I think the documented return value for `allel.sequence_diversity` might be wrong.  Seems like it should just be `float`.

The offending line is:
https://github.com/cggh/scikit-allel/blob/0fa09dd3cce23e781e2e7ef6e8870ee86cb6d62d/allel/stats/diversity.py#L227

**Comment by hardingnj** [comment]
This was resolved in #294
