### ISSUE TITLE
`sequence_diversity` does not mask `ac` when `is_accessible` provided

### ISSUE THREAD

**Issue by travc** [cggh/scikit-allel#276]
If you have a callest which includes variants outside the `is_accessible` mask, `sequence_diversity` still includes them in the numerator of the computation.

Ok, I get the that the normal workflow would be to exclude those loci from the genotype array, but the docs don't make it clear that it is necessary.  Plus it would be pretty cool/useful if `is_accessible` could be used as a more general mask in that function and others.

**Comment by alimanfoo** [comment]
Thanks Travis, yes sounds like this could be improved. I'll need to
reacquaint with that piece of code but if you have thoughts about how to
fix then please feel free to submit a PR or discuss here.

**Comment by mufernando** [comment]
This was fixed in #294
