### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by sagarendluri** [cggh/scikit-allel#295]
hi sir,
Not opening this site
http://alimanfoo.github.io/2017/06/14/read-vcf.html

**Comment by benjeffery** [comment]
Hi @sagarendluri ,
That link appears to work for me - what happens for you?

**Comment by sagarendluri** [comment]
actually ,i am newly working on genotype data
i dont have any knowliedge on that

**Comment by sagarendluri** [comment]
Thanks,
can you add  more about vcf file

**Comment by benjeffery** [comment]
If you mean more general info about VCF there is some [here](https://en.wikipedia.org/wiki/Variant_Call_Format) and lots of other places around the web if you search e.g. https://www.biostarhandbook.com/vcf.html
I'll close this issue as this tracker is for specific issues with `scikit-allele`. Thanks.

**Comment by sagarendluri** [comment]
hi Jeffery sir, i got this error

ValueError: path '22/samples' contains an array

**Comment by alimanfoo** [comment]
Dear @sagarendluri, we would like to help you but we need a lot more information. At the very least we need to know what you are trying to do, and we need to see the code that you wrote that generated this error. The best thing you could do would be to give us a **minimal reproducible self-contained example** which is a **short** snippet of code that we can run on our own computer and which generates this error. 

Please understand that our time is limited, and so the more information you can provide and the more specific your questions, the easier it will be for us to help. If your questions are vague or there is no information about how you generated an error, it is very unlikely we will be able to help.

**Comment by sagarendluri** [comment]
Thanks, I had done

**Comment by sagarendluri** [comment]
sir ,how to math genome sample to phenotype data
