### ISSUE TITLE
Converting genotype array to allel count encoding

### ISSUE THREAD

**Issue by jamesthegiantpeach** [cggh/scikit-allel#312]
Hi, thanks for this repo.

This is a noob question:

I have a numpy array of alleles encoded as A=[0,1,0,1,2,0]. These are the alleles i'm interested in, and I would like to use this to convert a genotype array GT[i,j] to the number of copies of A[i] for each cell in GT[i,:]. The end result should be a 2-dimensional numpy array with entries from {0,1,2}. This seems like a common conversion, and I was wondering if there's an efficient method for this using this library. Not immediately clear to me how to do this with numpy api.

**Comment by alimanfoo** [comment]
Hi @jamesthegiantpeach, just checking in to ask if you found a solution for this?

**Comment by jamesthegiantpeach** [comment]
Hi @alimanfoo 

I ended up just writing a C routine that extracted the info from a VCF file and encoded as apache arrow tensor. I wasn’t able to do it efficiently using only the numpy API. I’m sure there’s something obvious I missed.

**Comment by alimanfoo** [comment]
Thanks for checking back. FWIW I didn't fully grok the transformation you were after. It sounded a bit like you want to count the number of occurrences of a given allele within each genotype call, but I wasn't sure. Also FWIW scikit-allel has a [GenotypeArray.to_allele_counts()](https://scikit-allel.readthedocs.io/en/stable/model/ndarray.html#allel.Genotypes.to_allele_counts) method which does count alleles within genotype calls, which could then be queried for specific alleles. Anyway, sounds like I'm too late to be of any use, but thought I'd mention.
