### ISSUE TITLE
allel.pairwise_distance treats missing calls as litteral -1

### ISSUE THREAD

**Issue by feilchenfeldt** [cggh/scikit-allel#370]
Hello,

I am trying to calculate pairwise differences between sequences from a vcf with missing genotypes.
However, allel.pairwise_distance seems to treat missing genotypes at litteral -1. 

Here a minimal example of three (haploid) samples with two snps.

```
ht = allel.HaplotypeArray([[0, 0, -1],
                          [0, 1, -1]], dtype='i1')
d = allel.pairwise_distance(ht, metric='cityblock')
d_array = scipy.spatial.distance.squareform(d)
print(d_array)

[[0. 1. 2.]
 [1. 0. 3.]
 [2. 3. 0.]]
```

The last sample has all missing data. Still it has the largest distance to both other samples and is more distant to sample 2 than to sample 1.  While it is not totally obvious how to account for missing data, just treating missing data as litteral -1 can't be the right approach and might lead to false conclusing if people are not aware of this unexpected behaviour. 

In the absence of phasing or priors, I think the most sensible approach would be to count comparisons between two samples with one or both calls missing as zero (no difference) and then rescale each pairwise difference value by `number_of_comparisons/number_of_comparisons_with_non_missing_data`. I think this is also what plink does: [https://www.cog-genomics.org/plink/1.9/distance#distance](url)

Best wishes,
Hannes

**Comment by jeromekelleher** [comment]
Hi @feilchenfeldt :wave: - yes, we're currently building up the first "public" release of sgkit at the moment, it would be great if you could try it out and see how it works for you.

**Comment by feilchenfeldt** [comment]
@jeromekelleher I will give it a try! 
Does `sgkit.divergence` account correctly for missing data and heterozygous genotypes if my "cohorts" are gt calls of diploid individuals?

Cheers,
Hannes

**Comment by feilchenfeldt** [comment]
> Any bug reports/code contributions along those lines would be much appreciated @feilchenfeldt!

I will test `sgkit.divergence` when I have time and file a report if I think something could be improved, @jeromekelleher!
