### ISSUE TITLE
bug when giving count_alleles the max_allele argument 

### ISSUE THREAD

**Issue by hardingnj** [cggh/scikit-allel#59]
v.0.20.2

The counts seem to go haywire when the option is used. I've put some code in a notebook [here](http://ag1000g-dev.cggh.org/repo/notebooks/njh/2016_01_28-buginsciallel.html)

**Comment by alimanfoo** [comment]
Thanks Nick, I'll take a look asap.

On Thursday, January 28, 2016, Nick Harding <notifications@github.com>
wrote:

> The counts seem to go haywire when the option is used. I've put some code
> in a notebook here
> <http://ag1000g-dev.cggh.org/repo/notebooks/njh/2016_01_28-buginsciallel.html>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cggh/scikit-allel/issues/59>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721
