### ISSUE TITLE
to_n_ref() not filling with 0 for missing

### ISSUE THREAD

**Issue by travc** [cggh/scikit-allel#74]
`GenotypeArray.to_n_ref()` is sometimes outputting 1 for positions which are uncalled when fill is not given or set to 0.  Specifying a different fill returns that value as expected.
The docs for the function say that it should return 0 (default fill=0), but that is the one case which doesn't work.
ETA: `to_n_alt()` returns 0 for that position.  However, it has the same odd behavior as `to_n_ref`, just at different loci.

```
type(gfr)
allel.model.chunked.GenotypeChunkedArray

gfr.is_missing()[17,37]
True

gfr.is_called()[17,37]
False

gfr.to_n_ref()[17,37]
1

gfr.to_n_ref(fill=0)[17,37]
1

gfr.to_n_ref(fill=-1)[17,37] # works for any value I try other than 0
-1

gfr.to_n_alt()[17,37]
0
```

ETA: I'd like to be more helpful, but I can't actually find where that function is implemented in the code.

**Comment by alimanfoo** [comment]
Thanks Travis, I'm on leave next week but will look into this asap when
back.

On Friday, 12 February 2016, Travis Collier <notifications@github.com>
wrote:

> GenotypeArray.to_n_ref() is sometimes outputting 1 for positions which
> are uncalled when fill is not given or set to 0. Specifying a different
> fill returns that value as expected.
> The docs for the function say that it should return 0 (default fill=0),
> but that is the one case which doesn't work.
>
> type(gfr)
> allel.model.chunked.GenotypeChunkedArray
>
> gfr.is_missing()[17,37]
> True
>
> gfr.is_called()[17,37]
> False
>
> gfr.to_n_ref()[17,37]
> 1
>
> gfr.to_n_ref(fill=0)[17,37]
> 1
>
> gfr.to_n_ref(fill=-1)[17,37] # works for any value I try other than 0
> -1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cggh/scikit-allel/issues/74>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by travc** [comment]
No rush on my part.  Workaround is easy.

**Comment by alimanfoo** [comment]
Hi @travc, apologies for the very long hiatus. I'm just looking at this now, the only way I can figure this happens is if there is a half-missing genotype call, e.g., something like './0'. Could you confirm if the genotype call where you get an unexpected value of 1 for to_n_ref() is './.' or './0' or something else?

**Comment by travc** [comment]
Alas, I don't remember the full context and didn't do a very good job giving an example.

I do see the confusion with half-missing, though don't know how I'd get half-missing calls in any of the datasets this could have arisen from.

For that half-missing case, it is odd that `fill=0` or `None` has different behaviour from any other value.  Perhaps `fill=None` should count half-missing (if that is what you want) and `fill=0` should fill them?

**Comment by alimanfoo** [comment]
Thanks, my fault for taking so long to respond. I don't know of anyone who has half-missing calls but it was the only thing I could think of. I think I'll leave as-is for the moment but if you do hit this again then please feel free to re-open.
